#!/bin/bash

SECONDS=0

PROG=`basename $0`
if [ $# -ne 3 ]
then
    echo "Usage: ${PROG} [output.root] [/input/dir] [comment (centrality etc.)]"
    exit;
fi

outfile=${1}
indir=${2}
comment=${3} # comment to add to the correction file names, for example centrality, energy etc

./saveQvecs ${outfile} ${indir} ${comment} 0

cmd="root -b -q 'src/CalculateCorrections.C(\"${outfile}\", \"${comment}\")'"
eval $cmd

mv corr_*.txt corrections/.

duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."
