#!/bin/bash

PROG=`basename $0`
if [ $# -ne 9 ]
then
    echo "Usage: ${PROG} [output.root] [\input\dir] [comment (centrality etc.)]"
    exit;
fi

outfile=${1}
indir=${2}
comment=${3} # comment to add to the correction file names, for example centrality, energy etc

.\calcCorrections ${outfile} ${indir} ${comment} 0

cmd="root -b -q 'src/CalculateCorrections.C(\"${outfile}\", \"${comment}\")'"
eval $cmd

mv corr_*.txt corrections/.
