#!/bin/bash

SECONDS=0

PROG=`basename $0`
if [ $# -ne 4 ]
then
    echo "Usage: ${PROG} [output.root] [/input/dir] [comment (centrality etc.)] [docorrections (0/1)]"
    exit;
fi

outfile=${1}
indir=${2}
comment=${3}
docorr=${4}

declare -a kinefiles
for file in ${indir}/sim/*/o2sim_Kine_PPOnly.root
do
	kinefiles=(${kinefiles[@]} "$file")
done

declare -a fv0digitfiles
for file in ${indir}/dig_5Hz-mips8/*/fv0digits.root
do
	fv0digitfiles=(${fv0digitfiles[@]} "$file")
done

declare -a ft0digitfiles
for file in ${indir}/dig_5Hz-mips8/*/ft0digits.root
do
	ft0digitfiles=(${ft0digitfiles[@]} "$file")
done

nfiles=${#kinefiles[@]}

for (( i=0; i<$nfiles; i++ ))
do
    if [[ "$i" == "19" || "$i" == "20" || "$i" == "22" || "$i" == "34" ]]; then
        echo "Skip run ${ft0digitfiles["${i}"]}"
        continue
    fi
	cmd="root -b -q 'src/SaveQvecs.C(\"${kinefiles[i]}\", \"${fv0digitfiles[i]}\", \"${ft0digitfiles[i]}\", \"${outfile}\", \"${comment}\", \"${docorr}\")'"
	eval $cmd
done

duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."
